export const data = [
  {
    id: 1,
    image: 'https://i.ibb.co/ZJytjvM/Birthday-remainder.png',
    title: 'Birthday Remainder',
    link: 'https://birthday-remainder-app.netlify.app/',
  },
  {
    id: 2,
    image: 'https://i.ibb.co/RjM9kmM/Tour.png',
    title: 'Tour',
    link: 'https://tour-reactapp.netlify.app/',
  },
  {
    id: 3,
    image: 'https://i.ibb.co/rGX97LQ/Reviews.png',
    title: 'Reviews',
    link: 'https://review-reactapp.netlify.app/',
  },
  {
    id: 4,
    image: 'https://i.ibb.co/Yp6sxGt/Question.png',
    title: 'Questions',
    link: 'https://question-react-app.netlify.app/',
  },
  {
    id: 5,
    image: 'https://i.ibb.co/rkX0G2c/Menu.png',
    title: 'Menu',
    link: 'https://restaurants-menu-app.netlify.app/',
  },
  {
    id: 6,
    image: 'https://i.ibb.co/3ft0Yjr/Tabs.png',
    title: 'Tabs',
    link: 'https://tabs-react-app.netlify.app/',
  },
  {
    id: 7,
    image: 'https://i.ibb.co/5vLQqTD/Slider.png',
    title: 'Slider',
    link: 'https://slider-reactapp.netlify.app/',
  },
  {
    id: 8,
    image: 'https://i.ibb.co/3p3t4qG/Lorem-Ipsum.png',
    title: 'Lorem Ipsum',
    link: 'https://lorem-ipsum-generator-app.netlify.app/',
  },
  {
    id: 9,
    image: 'https://i.ibb.co/7j4RtKj/Color-shades.png',
    title: 'Color Generator',
    link: 'https://react-color-generator-app.netlify.app/',
  },
  {
    id: 10,
    image: 'https://i.ibb.co/30s1dVV/Grocery-Bud.png',
    title: 'Grocery Bud',
    link: 'https://react-grocery-bud-app.netlify.app/',
  },
  {
    id: 11,
    image: 'https://i.ibb.co/JHMXW5X/Navbar.png',
    title: 'Navbar',
    link: 'https://navbar-react-app.netlify.app/',
  },
  {
    id: 12,
    image: 'https://i.ibb.co/WVd474H/Sidebar-Modal.png',
    title: 'Slider / Modal',
    link: 'https://modal-sidebar-app.netlify.app/',
  },
  {
    id: 13,
    image: 'https://i.ibb.co/F44yx22/Stripe-menu.png',
    title: 'Stripe Submenu',
    link: 'https://stripe-menu-app.netlify.app/',
  },
  {
    id: 14,
    image: 'https://i.ibb.co/Rhp8Hxc/Mobile-cart.png',
    title: 'Mobile-Cart',
    link: 'https://mobile-cart-app.netlify.app/',
  },
  {
    id: 15,
    image: 'https://i.ibb.co/Rv1rxsS/Cocktail.png',
    title: 'Cocktails',
    link: 'https://cocktail-menu-app.netlify.app/',
  },
  {
    id: 16,
    image: 'https://i.ibb.co/4RhBFqQ/Markdown.png',
    title: 'Markdown',
    link: 'https://markdown-react-app.netlify.app/',
  },
  {
    id: 17,
    image: 'https://i.ibb.co/rMdnP80/Stock-photos.png',
    title: 'Stock Photos',
    link: 'https://stock-photos-app.netlify.app/',
  },
]
